config/routes.rb
Rails.application.routes.draw do

  resources :posts, only: [:new, :create, :index]
  resources :sessions, only: [:new, :create, :destroy]
  root 'posts#index'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  before_create :generate_remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def generate_remember_token
      self.remember_token = User.digest(User.new_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id 
    @post.save
    redirect_to root_path
  end

  def index
    @posts = Post.all
  end

  private

    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'Thank you for signing in!'
      log_in user
      redirect_to root_path
    else
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
    remember_token = User.new_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.digest(remember_token))
    self.current_user = user
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.digest(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    current_user.update_attribute(:remember_token,
                                User.digest(User.new_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to "Home", root_path %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<p>
<% if logged_in? %>
<%= link_to "(#{current_user.name}) Log out", logout_path, method: "delete" %>
<% else %>
  <%= link_to 'Log in', login_path %>
<% end %>
</p>

<h1>Members Only Posts</h1>

<% @posts.each do |post| %>
  <% if logged_in? %>
    <p>
      <i>Posted by:
      <%= post.user.name %></i>
    </p>
  <% end %>
  <h3><%= post.title %></h3>
  <p><%= post.body %></p>
  <p>
    --------------------------------------------------------------------------
  </p>
<% end %>

<% if logged_in? %>
  <%= link_to "Create a Post", new_post_path %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>

  <p>
    <%= f.label :title %> <br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %> <br />
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>